sudo: required
dist: trusty
language: cpp
matrix:
include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env: COMPILER=g++-4.9

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl libgtest-dev unzip valgrind rats cppcheck vera++
  - pushd /usr/src/gtest
  - sudo cmake .
  - sudo cmake --build .
  - sudo mv libg* /usr/local/lib/
  - popd
  - mkdir 3rdparty
  - pushd 3rdparty
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.1.zip
  - unzip sonar-scanner-2.6.1.zip
  - export PATH=$PWD/sonar-scanner-2.6.1/bin:$PATH
  - popd
script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make all unit_tests coverage_tests examples
  - popd
  - sonar-scanner -Dsonar.host.url=https://nemo.sonarqube.org -Dsonar.login=$SONAR_TOKEN