sudo: required
dist: trusty
language: cpp
matrix:
include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env: COMPILER=g++-4.9

before_install:
  - mkdir -p      $TRAVIS_BUILD_DIR/docs/reports/cppcheck       $TRAVIS_BUILD_DIR/docs/reports/gcov        $TRAVIS_BUILD_DIR/docs/reports/gtest
  - mkdir -p      $TRAVIS_BUILD_DIR/docs/reports/make           $TRAVIS_BUILD_DIR/docs/reports/oclint      $TRAVIS_BUILD_DIR/docs/reports/rats
  - mkdir -p      $TRAVIS_BUILD_DIR/docs/reports/valgrind       $TRAVIS_BUILD_DIR/docs/reports/vera++      $TRAVIS_BUILD_DIR/docs/reports/lcov
  - mkdir -p      $TRAVIS_BUILD_DIR/3rdparty                    $TRAVIS_BUILD_DIR/build

  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl libgtest-dev unzip valgrind rats cppcheck vera++ oclint
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo cmake --build .
  - sudo mv libg* /usr/local/lib/
  - cd $TRAVIS_BUILD_DIR/3rdparty
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.1.zip
  - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
  - unzip sonar-scanner-2.6.1.zip
  - unzip build-wrapper-linux-x86.zip
  - export PATH=$PWD/sonar-scanner-2.6.1/bin:$PWD/build-wrapper-linux-x86:$PATH
script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 2>&1 | tee ../docs/reports/make/cmake.log
  - build-wrapper-linux-x86-64 --out-dir . make clean all unit_tests coverage_tests examples
  - $TRAVIS_BUILD_DIR/build/tests/coverage_tests --xml:$TRAVIS_BUILD_DIR/docs/reports/gtest
  - $TRAVIS_BUILD_DIR/build/tests/unit_tests --xml:$TRAVIS_BUILD_DIR/docs/reports/gtest
  - cd $TRAVIS_BUILD_DIR/
  - sonar-scanner -Dsonar.host.url=https://nemo.sonarqube.org -Dsonar.login=$SONAR_TOKEN
