sudo: required
dist: trusty
language: cpp
matrix:
include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env: COMPILER=g++-4.9

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl libgtest-dev
  - pushd /usr/src/gtest
  - sudo cmake .
  - sudo cmake --build .
  - sudo mv libg* /usr/local/lib/
  - popd

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make all unit_tests coverage_tests examples
