language: cpp
install:
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl libgtest-dev cmake
  - pushd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; popd
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target unit_tests && cmake --build . --target coverage_tests && cmake --build . --target examples