sudo: required
dist: trusty
language: cpp
matrix:
include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env: COMPILER=g++-4.9

before_install:

  - if [ ! -e docs/reports/cppcheck ]; then mkdir -p docs/reports/cppcheck; fi
  - if [ ! -e docs/reports/gcov ]; then mkdir -p docs/reports/gcov; fi
  - if [ ! -e docs/reports/gtest ]; then mkdir -p docs/reports/gtest; fi
  - if [ ! -e docs/reports/make ]; then mkdir -p docs/reports/make; fi
  - if [ ! -e docs/reports/oclint ]; then mkdir -p docs/reports/oclint; fi
  - if [ ! -e docs/reports/rats ]; then mkdir -p docs/reports/rats; fi
  - if [ ! -e docs/reports/valgrind ]; then mkdir -p docs/reports/valgrind; fi
  - if [ ! -e docs/reports/vera++ ]; then mkdir -p docs/reports/vera++; fi
  - if [ ! -e docs/reports/lcov ]; then mkdir -p docs/reports/lcov; fi

  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl libgtest-dev unzip valgrind rats cppcheck vera++
  - pushd /usr/src/gtest
  - sudo cmake .
  - sudo cmake --build .
  - sudo mv libg* /usr/local/lib/
  - popd
  - mkdir 3rdparty
  - pushd 3rdparty
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.1.zip
  - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
  - unzip sonar-scanner-2.6.1.zip
  - unzip build-wrapper-linux-x86.zip
  - export PATH=$PWD/sonar-scanner-2.6.1/bin:$PWD/build-wrapper-linux-x86:$PATH
  - popd
script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 2>&1 | tee ../docs/reports/make/cmake.log
  - build-wrapper-linux-x86-64 --out-dir . make clean all unit_tests coverage_tests examples
  - popd
  - sonar-scanner -Dsonar.host.url=https://nemo.sonarqube.org -Dsonar.login=$SONAR_TOKEN
